
```{r, echo = FALSE}
knitr::opts_chunk$set(
    collapse = TRUE,
    comment = "#>",
    fig.path = "patrick-"
)
```


```{r}
## devtools::install_github("kbenoit/sophistication")
## devtools::install_github("patperry/r-frame")
library(corpus)
library(frame)
library(magrittr)
library(wordcloud)
options(format.limit = 30)

corpus <- as_corpus_frame(quanteda::data_corpus_inaugural)
text_filter(corpus)$drop_punct = TRUE
google1grams <- sophistication::data_matrix_google1grams
```


## Vanilla word cloud

```{r, fig.width = 12, fig.height = 12}
stats <- term_stats(corpus)
stats <- as.dataset(stats)
print(stats)
```

```{r}
with(stats[1:300,],
     wordcloud(term, count, random.order = FALSE, scale = c(6, .5)))
```

## No stop words

```{r, fig.width = 12, fig.height = 12}
print(subset(stats, !term %in% stopwords_en))

with(subset(stats, !term %in% stopwords_en),
     suppressWarnings(wordcloud(term, count, random.order = FALSE)))
```


## Relative to Google 1-grams

```{r}
x <- rowSums(google1grams)
i <- match(stats$term, names(x))
stats$google <- x[i]
stats$ratio  <- with(stats, count / google)
print(stats)
```

Order by ratio

```{r}
reorder(stats, desc = ratio)
```

Threshold count

```{r}
(subset(stats, count >= 5)
 %>% reorder(desc = ratio))
```

## Another wordcloud

```{r, fig.width = 12, fig.height = 12}
top <- (subset(stats, count >= 5)
        %>% reorder(desc = ratio))[1:300, ]
with(top, wordcloud(term, ratio, random.order = FALSE,
                    scale = c(10, .5)))
```
